### ISSUE TITLE
PERMISSIONS: make table scrollable to see all columns

### ISSUE THREAD

**Issue by jesscmoore** [anusii/solidpod#296]
## Describe the Bug

The Grant Permissions sharing page is missing the Actions column in the default app window size on macos platform. Permissions table needs to be horizontally scrollable.

## To Reproduce

1. cd notepod
2. flutter run --debug -d macos
3. Click on My Notes, select a note, click on sharing icon
4. The Actions column is not visible unless macos window is expanded
## Expected Behaviour

User should be able to see all columns

## Screenshots

With macos app default window size:

<img width="752" height="684" alt="Image" src="https://github.com/user-attachments/assets/dab69585-28ab-4037-b5af-b4ad94efb8b9" />

After increasing width:

<img width="881" height="996" alt="Image" src="https://github.com/user-attachments/assets/c5e4091d-9a02-4b90-bd12-473a19bdf746" />

## Context

Where has the issue been observed:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] macOS
 - [ ] Web
 - [ ] Windows

App Version: notepod 0..2.16 using solidpod pubdev and dev branches
Flutter Version: 3.32.7

## Closing Criteria

Checklist for closing the issue:

- [ ] User can tell they should scroll and are able to scroll to see all columns

**Comment by jesscmoore** [comment]
Initially tried editing desktop app window size. View after edits (pre scroll down):

<img width="1020" height="956" alt="Image" src="https://github.com/user-attachments/assets/37333337-525b-49a5-b0ec-6d7d620af594" />

And after scroll down:

<img width="1013" height="867" alt="Image" src="https://github.com/user-attachments/assets/16488a2d-0440-4f4f-b512-d781858dd960" />

**Comment by jesscmoore** [comment]
@gjwgit pointed out that adjusting window size was not the right solution. Transferring issue to solidpod to add scrolling to permissions table.

**Comment by jesscmoore** [comment]
This issue appeared in platforms with small display: iPadOS, macOS, iOS. Resolved with horizontal SingleChildScrollView(). As seen below:

MacOS after panning down and to right:

<img width="912" height="740" alt="Image" src="https://github.com/user-attachments/assets/86a90e95-5f9e-4169-b6bd-2e5980eac9f4" />

ipadOS after panning down and to right:

<img width="728" height="1021" alt="Image" src="https://github.com/user-attachments/assets/744f9c44-fb38-4089-aa8e-8a1c9859851f" />

Horizontal scrolling provided full width for longer recipient WebIDs, which removes the column overflow error in #297

**Comment by gjwgit** [comment]
I've merged to remove the overfull error. But I don't seem to see the horizontal scroll working.

<img width="895" height="819" alt="Image" src="https://github.com/user-attachments/assets/536c5c5f-ddd1-4e6e-a31b-7c9e4088dd63" />

**Comment by jesscmoore** [comment]
> I've merged to remove the overfull error. But I don't seem to see the horizontal scroll working.

@gjwgit Maybe I need to make it easier. Currently one needs to pan on the permissions table to scroll to right. However we could make it so that the singlechildscrollview wraps the whole page. Then one could pan from anywhere in the page. Although we'd also want to set the widget width for parts of the page, so they dont all expand.

It would be nice to modernise the UI for this page, eg the access type checkboxes and recipient type buttons - layout, sizing and design. On narrow portrait displays, eg iPhoneOS, the text in the buttons is truncated, and having to pan all around to much is not nice UX.

**Comment by gjwgit** [comment]
Yes, the page could be improved.

Not sure what `pan` means then. I've tried but still can't seem to get the scrollbar visible.

**Comment by jesscmoore** [comment]
@gjwgit I've added scrollbars (vertical on page, horizontal on table row) that are always visible where content exceeds display. Providing you wrap SingleChildScrollView() with Scrollbar() and provide ScrollController(), the scroll visibility can be set in the parent app themeData. Otherwise, it needs to be set in each Scrollbar(), as scroll visibility behaviour varies by platform.

```
MaterialApp(
      ...
      theme: ThemeData(
          primarySwatch: Colors.lightGreen,
          scrollbarTheme: ScrollbarThemeData(
            thumbVisibility: WidgetStateProperty.all(true),
          )),),
```

Iphone before and after scroll down on page, then scroll right on table:

<img width="505" height="1016" alt="Image" src="https://github.com/user-attachments/assets/92b86dac-5ce3-4b2e-b330-a355f8c0003a" />

<img width="505" height="1016" alt="Image" src="https://github.com/user-attachments/assets/2fcb4747-3a6f-43a7-9c78-1ecde1240f2c" />

<img width="505" height="1016" alt="Image" src="https://github.com/user-attachments/assets/0e766312-8c9a-467a-8780-f77bef749642" />

**Comment by jesscmoore** [comment]
> Not sure what `pan` means then. I've tried but still can't seem to get the scrollbar visible

On my mac, panning is a mouse drag to scroll in a scrollable widget.

**Comment by gjwgit** [comment]
Didn't seem to work for me on Linux. I seem to recall that previously too. I think it works with the touchpad though.

Thanks for the updates. Working well.

I've published to pub.dev.
