### ISSUE TITLE
SOLIDPOD: Revoke permission of previously shared folder removes owner's access to the folder

### ISSUE THREAD

**Issue by cdawei** [anusii/solidpod#462]
## Describe the Bug

Revoke the permission of a previously shared folder will change the ACL of the folder such that the owner can no longer access it.

## To Reproduce

1. Use the example app of the current `dev` branch
2. Login with `WEBID1` and `WEBID2`, respectively. This is to initialise the default folder structure.
3. Login with `WEBID1`, click `Create Resource with ACL Inheritance`, set resource path to `dir1/dir2/file1.ttl` and parent directory to `dir1/`, click `Create resource`.
4. Go to home page, click `Read Resource with ACL Inheritance`, set resource path to `dir1/dir2/file1.ttl`, and click `read resource`. The resource can be read without any problem.
5. Go to home page, click `Add/Delete Permission from Any Resource`, and grant `Read` access to `dir1` to `WEBID2`.
6. Then on the same page, revoke that `Read` access.
7. Go to step 4, access resource `dir1/dir2/file1.ttl` leads to error `Error reading file: Exception: Unknown error.`.
ACL file contents are shown below.

`dir1/.acl` after step 3:
```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix : <#> .
@prefix acl: <http://www.w3.org/ns/auth/acl#> .
@prefix c0: <https://solid.dev.empwr.au/dc101/profile/card#> .

:Read
    a acl:Authorization ;
    acl:accessTo <./> ;
    acl:default <./> ;
    acl:agent c0:me ;
    acl:mode acl:Read .
:Write
    a acl:Authorization ;
    acl:accessTo <./> ;
    acl:default <./> ;
    acl:agent c0:me ;
    acl:mode acl:Write .
:Control
    a acl:Authorization ;
    acl:accessTo <./> ;
    acl:default <./> ;
    acl:agent c0:me ;
    acl:mode acl:Control .
```

`dir1/.acl` after step 5:
```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix : <#> .
@prefix acl: <http://www.w3.org/ns/auth/acl#> .
@prefix c0: <https://solid.dev.empwr.au/dc101/profile/card#> .
@prefix c1: <https://solid.dev.empwr.au/dc105/profile/card#> .

:Read
    a acl:Authorization ;
    acl:accessTo <./> ;
    acl:default <./> ;
    acl:agent c0:me, c1:me ;
    acl:mode acl:Read .
:Write
    a acl:Authorization ;
    acl:accessTo <./> ;
    acl:default <./> ;
    acl:agent c0:me ;
    acl:mode acl:Write .
:Control
    a acl:Authorization ;
    acl:accessTo <./> ;
    acl:default <./> ;
    acl:agent c0:me ;
    acl:mode acl:Control .
```

`dir1/.acl` after step 6:
```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix : <#> .
@prefix acl: <http://www.w3.org/ns/auth/acl#> .
@prefix c0: <https://solid.dev.empwr.au/dc101/profile/card#> .

:Read
    a acl:Authorization ;
    acl:accessTo <> ;
    acl:agent c0:me ;
    acl:mode acl:Read .
:Write
    a acl:Authorization ;
    acl:accessTo <> ;
    acl:agent c0:me ;
    acl:mode acl:Write .
:Control
    a acl:Authorization ;
    acl:accessTo <> ;
    acl:agent c0:me ;
    acl:mode acl:Control .
```

## Expected Behaviour

Resource `dir1/dir2/file1.ttl` should be accessed without problems.

## Context

Where has the issue been observed:

- [ ] Android
- [ ] Chrome
- [ ] iOS
- [x] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

**Comment by cdawei** [comment]
Thanks @anushkavidanage for pointing out the difference between the default ACL of file and directory, it seems indeed the `isFile` argument needs to be used when revoking permission here 

https://github.com/anusii/solidpod/blob/09c0e503356bfe081d2e7ad0c4e972f2b70b40a6/lib/src/solid/revoke_permission.dart#L141

**Comment by gjwgit** [comment]
@anushkavidanage to confirm this has been fixed. If so please close.

**Comment by gjwgit** [comment]
@anushkavidanage will check and then close.

**Comment by anushkavidanage** [comment]
I cannot test this in the current `dev` branch due to an issue with sharing inherited resources. Will create new issues around this issue.

**Comment by gjwgit** [comment]
BLOCKED: This can not be tested until inheritance is sorted out. Could be due to recent sharing/permission changes.

**Comment by anushkavidanage** [comment]
In the example app I still cannot grant permissions to inherited resources. When I try to grant permission to a folder I get the following error.

<img width="1524" height="825" alt="Image" src="https://github.com/user-attachments/assets/ee74bcde-42a9-4f5c-be5f-5ab566cb88f2" />

**Comment by gjwgit** [comment]
Noting it works in riopod using direct function call. @anushkavidanage will further test/debug.
